name: my_school
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  firebase_core: ^3.1.1
  firebase_database: ^11.0.2
  google_fonts: ^4.0.4
  syncfusion_flutter_charts: ^24.2.7
  cloud_firestore: ^5.0.2
  webview_flutter: ^2.0.10
  http: ^0.13.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
