// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPcaH_vvKo1VwpHzcLcoAmU5bdSDdUtww',
    appId: '1:659155946969:web:bdc9a0e044c91d2611ddc8',
    messagingSenderId: '659155946969',
    projectId: 'hour-of-code-e68f6',
    authDomain: 'hour-of-code-e68f6.firebaseapp.com',
    databaseURL: 'https://hour-of-code-e68f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hour-of-code-e68f6.appspot.com',
    measurementId: 'G-RPN01WHB6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Czs_D0LjNubVfkjbPn4SkOXURE6RBgQ',
    appId: '1:659155946969:android:3cc792015ae300b211ddc8',
    messagingSenderId: '659155946969',
    projectId: 'hour-of-code-e68f6',
    databaseURL: 'https://hour-of-code-e68f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hour-of-code-e68f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TRrscBJL988htWkjTZCzx2S17oiqtsI',
    appId: '1:659155946969:ios:5d56da1948d85f7711ddc8',
    messagingSenderId: '659155946969',
    projectId: 'hour-of-code-e68f6',
    databaseURL: 'https://hour-of-code-e68f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hour-of-code-e68f6.appspot.com',
    iosBundleId: 'com.example.mySchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7TRrscBJL988htWkjTZCzx2S17oiqtsI',
    appId: '1:659155946969:ios:5d56da1948d85f7711ddc8',
    messagingSenderId: '659155946969',
    projectId: 'hour-of-code-e68f6',
    databaseURL: 'https://hour-of-code-e68f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hour-of-code-e68f6.appspot.com',
    iosBundleId: 'com.example.mySchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPcaH_vvKo1VwpHzcLcoAmU5bdSDdUtww',
    appId: '1:659155946969:web:41099bc8d75c587611ddc8',
    messagingSenderId: '659155946969',
    projectId: 'hour-of-code-e68f6',
    authDomain: 'hour-of-code-e68f6.firebaseapp.com',
    databaseURL: 'https://hour-of-code-e68f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hour-of-code-e68f6.appspot.com',
    measurementId: 'G-6G63SW2D4Z',
  );
}
